集金日の変更
rogy-AquaLab/2023_robokit pull request #43
Opened 2023-05-11 07:55 UTC by saitenntaisei

2023-05-11 08:19 UTC, H1rono requested changes
formatter使ってますか？余計な空白が気になるので消して欲しいです

2023-05-11 13:27 UTC, saitenntaisei commented
mdのformattter is 何?

2023-05-11 13:31 UTC, H1rono commented
んー、PrettierのVSCode拡張機能とかかな
それか[markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)とか別の拡張機能が入ってるとか
とにかく空白の変更をrevertして欲しいです

2023-05-12 06:47 UTC, H1rono commented
直ったらre-request reviewして欲しいです

2023-05-12 06:47 UTC, saitenntaisei commented
全部入ってたけどむしろそれが悪さして勝手にformatされたみたい?
とりあえず直した

2023-05-12 06:49 UTC, H1rono approved these changes
LGTM 👍 
マージして大丈夫です

2023-05-12 06:59 UTC, merged